# CI Workflow for MFC running Ascent @ ORNL through GitLab.

# GitLab: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
#  - User Set:
#    - $GIT_STRATEGY: none -> Runner should not clone repository before executing script
#  - User Read:
#    - $CI_PROJECT_NAME   -> e.g MFC, MFC-develop, ...
#    - $CI_REPOSITORY_URL -> e.g https://gitlab-ci-token:[MASKED]@code.ornl.gov/ecpcitest/cfd154/MFC-develop.git
#    - $CI_COMMIT_BRANCH  -> e.g GPU, master, ...
# ORNL's Ascent:
#  - User Set:
#    - $SCHEDULER_PARAMETERS
#  - User Read:
#    - $MEMBERWORK -> e.g /gpfs/wolf/scratch/henrylb

stages:
  - clone # Clone MFC after removing artifacts from previous run(s). 
  - cpu   # Build MFC & Test it on/with CPUs
  - gpu   # Build MFC & Test it on/with GPUs

# Variables for all jobs
variables:
  # Tell runner to not clone MFC
  GIT_STRATEGY: none 
  # Ascent Job Scheduler parameters
  SCHEDULER_PARAMETERS: "-P CFD154 -nnodes 1 -W 00:30"

# This script runs before each job's main script is executed.
# It defines useful environment variables used at runtime.
before_script:
  # Check "$CI_PROJECT_NAME" contains "MFC" so we are sure
  # we won't clone into or delete from an unsuspecting directory
  # due to an unfortunate error.
  - echo "[CI] Running fin $(pwd):"
  - if [[ ! "$CI_PROJECT_NAME" == *"MFC"* ]]; then exit 1; fi;

  # Define MFC directory path
  - CI_MFC_DIR="$MEMBERWORK/cfd154/.ci/$CI_PROJECT_NAME/$CI_COMMIT_BRANCH"

# Clone MFC after removing artifacts from previous run(s). 
clone-job:
  stage: clone
  script:
    # Clean MFC directory if it exists (from a previous run)
    - if [ -d "$CI_MFC_DIR" ]; then rm -rf "$CI_MFC_DIR"; fi 
    # Create empty MFC directory
    - mkdir -p "$CI_MFC_DIR"

    # Clone MFC into MFC directory & cd into it
    - git clone --single-branch --branch "$CI_COMMIT_BRANCH" "$CI_REPOSITORY_URL" "$CI_MFC_DIR/"
    - cd "$CI_MFC_DIR" && echo "[CI] Running in $(pwd):"
  tags:
    - nobatch

cpu-build-job:
  stage: cpu
  script:
    - cd "$CI_MFC_DIR" && echo "[CI] Running in $(pwd):"
    - . ./mfc.sh load -c a -m g
    - ./mfc.sh build -j 8 -m release-cpu
  tags:
    - nobatch

cpu-test-job:
  stage: cpu
  needs:
    - cpu-build-job
  script:
    - cd "$CI_MFC_DIR" && echo "[CI] Running in $(pwd):"
    - . ./mfc.sh load -c a -m g
    - ./mfc.sh test -j 8
  tags:
    - batch

gpu-build-job:
  stage: gpu
  script:
    - cd "$CI_MFC_DIR" && echo "[CI] Running in $(pwd):"
    - . ./mfc.sh load -c a -m g
    - ./mfc.sh build -j 8 -m release-gpu
  tags:
    - nobatch

gpu-test-job:
  stage: gpu
  needs:
    - gpu-build-job
  script:
    - cd "$CI_MFC_DIR" && echo "[CI] Running in $(pwd):"
    - . ./mfc.sh load -c a -m g
    - ./mfc.sh test -j 8
  tags:
    - batch
